
[Thruster]
	#Particle additional velocity modifier when ship is moving in the same direction as exhaust.
	"Particle velocity offset" = 0.15
	#The higher this number is - the more particles are spawned.
	"Particle count multiplier" = 1.0

[Propeller]
	#Should fast-rotating propeller blades be blurred. Disable this if you experience visual issues with fast-rotating propellers
	"Enable blur" = true
	#Maximum amount of blurred models rendered. Decrease this value if your fps drops when near a lot of propellers.
	"Max blur instances" = 64
	#How slow propeller blades start to become blurry
	"Sample rate" = 2.0
	#Distance at which propllers no longer blur
	LOD = 128.0
	#Simulated exposure time. Set to 1/120 by default
	"Exposure time" = 0.008333333333333333
	#Angle of the propeller's blade, in degrees
	"Blade angle" = 10.0

["Stirling Engine"]
	#Revolution period of the simulated shaft (affects only piston movement).
	"Revolution period" = 0.2
	#Radius of the simulated crank.
	"Crank radius" = 0.125
	#Length of the simulated conrod.
	"Conrod length" = 0.5

["Hot air balloons"]
	#If true - hot air balloon particles will be spawned and rendered.
	"Enable balloon particles" = true
	#Multiplier for the amount of particles spawned inside the balloon volume. Higher values look better but may impact performance.
	"Volume particle spawn rate" = 1.0
	#Radius around the player in which balloon particles are simulated. Increasing this will reduce performance.
	#Range: 16.0 ~ 128.0
	"Particle simulation radius" = 32.0
	#Strength of the air jet ejecting particles from balloon holes.
	"Hole eject strength" = 2.8
	#How much ship inertia affects particle movement. Higher values make particles lag behind the ship movement more noticeable.
	"Inertia scale" = 0.5
	#Opacity of balloon particles. 0 is invisible, 255 is fully opaque.
	#Range: 0 ~ 255
	"Particle opacity" = 100
	#Multiplier for the rate at which the Hot Air Burner spawns heat stream particles.
	"Burner particle spawn multiplier" = 0.1
	#Multiplier for the rate at which the Hot Air Pump spawns heat stream particles.
	"Pump particle spawn multiplier" = 0.12

