name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fda540832e857455995371e8ded35946d8a30c354cc711030962471cc224453"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
