name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "421c9da8b6ab80b86ff7559c239128743274bf114131ecfae1e87cf36e746a9d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
