name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "074b4b2e1833a147d3b29f6f9e786d0c58d6e5b2793810135e8ac21ffaa03f11"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
