name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac11654b4c5ac8714b47c5fed1ace94b3b47e6063dd069ed19ebd7d7e499c4cf"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
