name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e8203997fd23ee34870a46c71dc777586cf39865dee5ffffb46fb219960e14b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
