name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "531b0b3a15604c048c60fda6a933e512daccfa59677ae85a8fd046a27425f62e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
