name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5f46fae5884341fa0c153868e952a66824825898ddcd663a9b54801119543d1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
