name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91f1f781fa317eedfdb2d9aa4d8d6ba7c64276b3ecec4376856745769290af0a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
