name = "flashgnash-atm9"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35332cc2a4b616422a402c9752c8b73ecda79cd8008bd509545a045bb36e4df6"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
